UserOfficeProject/user-office-backend

src/middlewares/graphql.ts
src/queries/UserQueries.ts
src/resolvers/federationSources.ts
src/resolvers/types/User.ts

- Made User type to be accessible from other services
- Apollo federation fixes

SWAP-1044 Scheduled event crud

---

package-lock.json
package.json

Updating to stable ts-node-dev

ts-node-dev@1.0.0

---

src/datasources/mockups/SampleDataSource.ts
src/models/Sample.ts

Resolving story: As a sample reviewer I want different statuses
Instead of evaluating sample with SAFE/UNSAFE have statues LOW RISK/ELEVATED RISK/HIGH RISK

SWAP-1102 More statues #resolved

---

src/models/Proposal.ts

Adding a comment to proposal statuses

Add comments to statuses

---

src/datasources/postgres/UserDataSource.ts
src/decorators/ValidateArgs.ts
src/mutations/UserMutations.ts

During user creation return `account exists` on unique constraint violation
https://jira.esss.lu.se/browse/SWAP-115
- check error type and code when user creation fails
https://github.com/UserOfficeProject/user-office-frontend/pull/118

SWAP-115 Trying to signup with taken username results in exception

---

package-lock.json
package.json
src/decorators/ValidateArgs.ts
src/mutations/CallMutations.ts
src/utils/helperFunctions.ts

Create/Update call validation schemas updated and split to fit the frontend needs. Here we just merge them and apply everything at once
The point is to have step validation on the frontend and full validation on the backend.
With e2e tests on the frontend.
https://jira.esss.lu.se/browse/SWAP-982
https://github.com/UserOfficeProject/user-office-lib/pull/18

SWAP-982 #resolve and fix some call validation problems

---

db_patches/db_seeds/0001_ProposalForScheduling.sql

DB seed fixed (sep_id removed)

Db seed fixed (sep_id removed)

---

docker-compose.yml

Adding factory initialization back

Adding factory initialization back

---

src/datasources/postgres/ProposalDataSource.ts
src/resolvers/queries/ProposalsQuery.ts
src/resolvers/queries/ProposalsViewQuery.ts

Adding new filter parameter `shortCode` when querying the proposals.
There is a need to be able to get the proposal by `shortCode`.
Manual testing
https://jira.esss.lu.se/browse/SWAP-1294
Just adding support to filter proposals by `shortCode`

SWAP-1294 #resolved

---

src/datasources/postgres/SEPDataSource.ts

This PR cleans up SEP_* tables when an assigned proposal is removed from a SEP.
The current version only removed the rows from `SEP_Assignments` but kept the reviews, this could result in a state where assigning a proposal to the same SEP we already had reviews, so during reviewer assignment, the request would fail with unique key constraint violation error.
- cleans up SEP_* tables in a transaction when an assigned proposal is removed from a SEP.

SEP Bugfix: Remove reviews when assigned proposal is removed

---

src/datasources/SampleDataSource.ts
src/datasources/postgres/QuestionaryDataSource.ts
src/datasources/postgres/SampleDataSource.ts
src/mutations/SampleMutations.spec.ts
src/mutations/SampleMutations.ts
src/utils/SampleAuthorization.ts

This PR fixes sample cloning in questionaries by copying completed topics also.
https://jira.esss.lu.se/browse/SWAP-1319
- copy completed topics
- fix possible null crash
- wait for user rights lookup to resolve
- sort samples by `created_at` so it fixes the jumping and reordering behavior on FE.
https://github.com/UserOfficeProject/user-office-frontend/pull/222

SWAP-1319 Cloning the sample the topics are incomplete

---

package-lock.json
package.json

This PR updates the @esss-swap/duo-validation updated package which fixes the validation of creating sep form.
https://jira.esss.lu.se/browse/SWAP-1343
- missing validation added
https://github.com/UserOfficeProject/user-office-frontend/pull/228

SWAP-1343 When creating a new SEP the activate button can't be pressed

---

db_patches/0079_AddMissingPrimaryKeys.sql

This PR adds missing primary keys and also removes some unnecessary unique constraints.
https://jira.esss.lu.se/browse/SWAP-1371
- missing primary keys added

SWAP-1371 Few tables have no Primary Keys

---

src/factory/pdf/proposal.ts
src/models/TechnicalReview.ts

This PR fixes the technical review status rendered in PDF.
Currently, it uses the enum value.
- added human-readable version

Use human readable technical review status in PDFs

---

src/mutations/SEPMutations.ts

Reverts UserOfficeProject/user-office-backend#182

Revert "Hot fix for SEP assigment"

---

src/models/questionTypes/Interval.ts
src/models/questionTypes/NumberInput.ts
src/resolvers/types/FieldConfig.ts

This PR fixes the Number and Interval questionary component validation rules.
https://jira.esss.lu.se/browse/SWAP-1394
- Number questionary  component validation rules updated
- Interval questionary  component validation rules updated
- Number questionary  component rendering fixed (don't display null values)
https://github.com/UserOfficeProject/user-office-frontend/pull/250

SWAP-1394 Number/interval input not working if required and does not have a unit

---

package-lock.json

Dependencies fixed

---

src/datasources/postgres/ReviewDataSource.ts

This PR fixes the SEP reviews filtering
- explicitly check if the value is defined or not

Fix reviews filtering

---

src/datasources/postgres/ReviewDataSource.ts

fix reviews filter

---

src/datasources/ReviewDataSource.ts
src/datasources/mockups/ReviewDataSource.ts
src/datasources/postgres/ReviewDataSource.ts
src/mutations/ReviewMutations.ts
src/populate/index.ts
src/resolvers/mutations/AddTechnicalReviewMutation.ts

User officer should be able to re-open submitted technical review.
Previously when technical review was submitted there was no way to reopen it.
manual and e2e tests
https://jira.esss.lu.se/browse/SWAP-1406

SWAP-1406 #resolved

---

src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/mutations/ProposalMutations.ts

Fix for cloning the co-proposers together with the proposal. The samples copy should be discussed and we should find better solution how to do it.
Co-proposers not being copied once we clone proposal.
e2e tests
https://jira.esss.lu.se/browse/SWAP-1447

Fix the co-proposer copy bug.

---

src/datasources/postgres/ProposalDataSource.ts

This PR fixes backend part for filtering proposals by questions

Add filter for instrument scientist as well

---

db_patches/db_seeds/0001_ProposalForScheduling.sql

This PR adds db seeds for e2e tests
https://jira.esss.lu.se/browse/SWAP-1501
- db seeds added for e2e test
https://github.com/UserOfficeProject/user-office-scheduler-backend/pull/24
https://github.com/UserOfficeProject/user-office-frontend/pull/296
https://github.com/UserOfficeProject/user-office-scheduler-frontend/pull/25

SWAP-1501 Scheduler crashes when 'YMIR' instrument is selected

---

db_patches/0085_Insert_Into_Proposal_Statuses_Table.sql

fix missing column in adding EDITABLE_SUBMITTED. This fixes useroffice-test

add missing column

---

src/datasources/postgres/UserDataSource.ts

Fixes a small bug that means an STFC user (using external auth) cannot log in after the first time.
Fixes https://github.com/UserOfficeProject/stfc-user-office-project/issues/107

Fix external auth failure after first login

---

src/resolvers/mutations/ResetPasswordEmailMutation.ts

Fix bug with wrong response returned for `resetPasswordEmail` mutation.
e2e tests
manual tests
https://jira.esss.lu.se/browse/SWAP-1535

SWAP-1535 #resolved

---

env-loader.js

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/136
A small change to `NODE_ENV` in the `env-loader.js` file so it can still run when the environment is undefined and just uses an empty string so the `.env` file can be used instead.

Update config to run with undefined environment

---

src/middlewares/graphql.ts

Hotfix schema corruption by graphql-middleware

hotfix: fix schema corruption

---

src/datasources/postgres/UserDataSource.ts
src/eventHandlers/messageBroker.ts

Send message to rabbitMQ message broker when proposal is accepted.
- The type of the data contained in the message is: 
`type ProposalAcceptedMessage = {
proposalId: number;
shortCode: string;
title: string;
members: { firstName: string; lastName: string; email: string }[];
proposer?: { firstName: string; lastName: string; email: string };
};`
- The event type is: `Event.PROPOSAL_ACCEPTED`
manual tests
https://jira.esss.lu.se/browse/SWAP-1608

Swap 1608 send proposal accepted message broker

---

src/datasources/postgres/ReviewDataSource.ts

Fixed some errors when trying to get user with reviews.
When getting user with reviews and trying to change call or instrument filter there was error in the database query.
https://jira.esss.lu.se/browse/SWAP-1438

Fixed error when getting user with reviews

---

src/models/questionTypes/Boolean.ts
src/models/questionTypes/Date.ts
src/models/questionTypes/Embellishment.ts
src/models/questionTypes/FileUpload.ts
src/models/questionTypes/Interval.ts
src/models/questionTypes/NumberInput.ts
src/models/questionTypes/ProposalBasis.ts
src/models/questionTypes/QuestionRegistry.ts
src/models/questionTypes/RichTextInput.ts
src/models/questionTypes/SampleBasis.ts
src/models/questionTypes/SampleDeclaration.ts
src/models/questionTypes/SelectionFromOptions.ts
src/models/questionTypes/ShipmentBasis.ts
src/models/questionTypes/TextInput.ts
src/models/questionTypes/VisitationBasis.ts

Instead of keeping the documentation about Questionary component signature in GitHub Wikis, the documentation has been moved into the source code. This will help with maintenance so that documentation is up to date, as well as with IDE intellisense.
SWAP-1566
https://github.com/UserOfficeProject/user-office-frontend/pull/396

patch(questionary):  Moving documentation in the code

---

src/datasources/InstrumentDataSource.ts
src/datasources/mockups/InstrumentDataSource.ts
src/datasources/postgres/InstrumentDataSource.ts
src/mutations/InstrumentMutations.spec.ts
src/mutations/InstrumentMutations.ts
src/resolvers/mutations/AssignProposalsToInstrumentMutation.ts

Improve removing proposal from instrument so we should be able to remove multiple proposals from an instrument at once.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-1434

Improve assigning and removing proposals to/from instrument

---

db_patches/0096_RenameVisitationToVisit.sql

Fix patch that threw an exception

patch: fix problematic db patch

---

db_patches/0098_MakeAllRolesShortCodesConsistent.sql
src/datasources/UserDataSource.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/mockups/UserDataSource.ts
src/datasources/postgres/UserDataSource.ts
src/datasources/stfc/StfcUserDataSource.ts
src/models/Role.ts
src/mutations/UserMutations.ts

Fixing bug with user invitation and improving some logic when user is invited with `SEP_reviewer` role. Also making all role short codes consistent because some were uppercase some lowercase.
manual tests
e2e tests
https://jira.esss.lu.se/browse/SWAP-1612

fix: bugfix for inviting users and improve some logic

---

src/eventHandlers/messageBroker.ts

Add `PROPOSAL_UPDATED` event to the message broker and add proposal abstract to `PROPOSAL_ACCEPTED` event.
https://jira.esss.lu.se/browse/SWAP-1638

Swap 1638 abstract to proposal accepted event

---

package.json
src/datasources/postgres/VisitDataSource.ts
src/mutations/TemplateMutations.ts
src/queries/VisitQueries.ts
src/resolvers/queries/VisitsQuery.ts
src/resolvers/types/Proposal.ts
src/resolvers/types/Visit.ts

This PR adds an indication to upcoming experiments that the user needs to register for a visit. 
This PR is the first iteration for the "traffic light system" which will clearly indicate to the user steps user needs to finish in order to complete preparation for the visit.
This PR adds functionality that if there is no visit registered for the experiment, then it shows a dot badge icon for the "Define your own visit" which when clicked opens the register for the visit page
SWAP-1631
https://github.com/UserOfficeProject/user-office-frontend/pull/423

feat(visits): Get visistations for proposal

---

db_patches/0076_CreateFeatureToggle.sql
db_patches/0084_AddSchedulerFeatureId.sql
db_patches/0092_SetAuthFeature.sql
index.ts
src/config/Tokens.ts
src/config/dependencyConfigE2E.ts
src/config/dependencyConfigESS.ts
src/config/dependencyConfigSTFC.ts
src/config/dependencyConfigTest.ts
src/datasources/AdminDataSource.ts
src/datasources/mockups/AdminDataSource.ts
src/datasources/postgres/AdminDataSource.ts
src/utils/enableDefaultFeaturesForDevelopment.ts

This PR aims to fix the issue of different facilities needing different features enabled/disabled by default.
It uses dependency injections where different functions implementing features enabling are run depending on the facility.
N/A

patch: Differentiate features #suggestion

---

db_patches/0099_AddProposalReservedEvent.sql
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/records.ts
src/eventHandlers/proposalWorkflow.ts
src/events/applicationEvents.ts
src/events/event.enum.ts

Added proposal reserved event in the proposal workflow.
manual tests
e2e tests
https://jira.esss.lu.se/browse/SWAP-1604

feat(proposal events): Add proposal_reserved event in the system

---

src/utils/UserAuthorization.ts

patch: fix access token issue

---

index.ts
src/config/Tokens.ts
src/config/dependencyConfigE2E.ts
src/config/dependencyConfigESS.ts
src/config/dependencyConfigSTFC.ts
src/config/dependencyConfigTest.ts
src/config/ess/enableDefaultEssFeatures.ts
src/config/ess/setEssColourTheme.ts
src/config/stfc/enableDefaultStfcFeatures.ts
src/config/stfc/setStfcColourTheme.ts
src/datasources/AdminDataSource.ts
src/datasources/mockups/AdminDataSource.ts
src/datasources/postgres/AdminDataSource.ts
src/mutations/AdminMutations.ts
src/utils/configureDevelopmentEnvironment.ts

Enabling a site-specific theme in the development
https://github.com/UserOfficeProject/user-office-frontend/pull/475

patch: Enable development theming per site

---

db_patches/0099_ExperimentPreparationAlterings.sql

fix: hotfix for test server

---

src/mutations/ProposalMutations.ts

fixes bug where proposal was returned before modifications for the proposal users was made

fix: wait for proposal users to be saved

---

src/mutations/ProposalMutations.ts
src/resolvers/mutations/CloneProposalMutation.ts

This PR shifts around code so that the SDK generated is the same on local as when running in pipeline
sdk
https://github.com/UserOfficeProject/user-office-frontend/pull/510

fix: fix SDK

---

src/datasources/stfc/StfcUserDataSource.ts

Closes https://github.com/UserOfficeProject/stfc-user-office-project/issues/161
- Amended the `StfcUserDataSource` to add and assign new roles

Added roles in the new proposal system

---

CONTRIBUTING.md

fix:contributing-guide-typo

---

.github/workflows/build-push.yml

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/142
- Created [Jenkins Job](https://ci.devs.facilities.rl.ac.uk/job/Dev_Deploy_ProposalBackend.LatestImage/) to trigger which triggers the kubernetes rollout for the backend. 
- Jenkins Job triggers when push to `master` or `develop` branch on the GitHub repo `user-office-backend` happens
- After Jenkins job was created, manually triggered and made sure it was successful. 
- Then triggered the job remotely with a curl command on GitBash 
- Added the command to `build-push.yml` file, created a branch and pushed to the branch to ensure the Jenkins Job was successfully triggered. 
Image above shows GitHub actions has taken place after push was made. 
Build was triggered successfully on Jenkins
Command on job has …

142 trigger deployment

---

db_patches/0106_AddTitleAndDescriptionToCall.sql
src/datasources/mockups/CallDataSource.ts
src/datasources/postgres/CallDataSource.ts
src/datasources/postgres/records.ts
src/middlewares/graphql.ts
src/models/Call.ts
src/mutations/CallMutations.spec.ts
src/populate/index.ts
src/resolvers/mutations/CreateCallMutation.ts
src/resolvers/mutations/UpdateCallMutation.ts
src/resolvers/types/Call.ts

Refs UserOfficeProject/stfc-user-office-project#202
Add title and description that can be stored with a call.
See https://github.com/UserOfficeProject/user-office-frontend/pull/559
Updated and ran unit tests. Manually tested in https://github.com/UserOfficeProject/user-office-frontend/pull/559.
Closes UserOfficeProject/stfc-user-office-project#202

feat: add long title and description to call

---

src/eventHandlers/messageBroker.ts

Closes UserOfficeProject/stfc-user-office-project#227
The RabbitMQ broker will now be initialised only if the broker was enabled in the dependency injection config. Both the listener and poster use the same broker, which is cached to a variable and only recreated when needed.
This prevents STFC logs from being full of mostly irrelevant messages about failing to initialise RabbitMQ.

fix: create RabbitMQ broker only when necessary

---

db_patches/0110_RemoveOutdatedCategories.sql

This fix removes outdated categories
- Experiment ESI
- Sample ESI
Data attached to these categories has been already migrated
For more information read on our Slack channel
https://ess-eric.slack.com/archives/G019J2U53U2/p1634218540030400

fix: remove outdated template categories

---

src/datasources/stfc/StfcUserDataSource.ts

Closes #225
Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/255
The Co proposers keep disappearing after saving and moving onto the next page. They do not show up in the final review section either.
I tested my changes by logging onto the site locally and adding co proposers and checking if they appear after I continue to the next page. 
Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/255
Made changes in `StfcUserDataSource.ts` - added null checks and made method calls to `ensureDummyUserExists()` to relevant methods.

fix: Co-proposers no longer disappear after saving

---

src/datasources/stfc/StfcUserDataSource.ts

Renames the environment variable for the UserOfficeWebService.

Rename UserOfficeWebService environment var

---

src/datasources/stfc/StfcUserDataSource.ts

This reverts commit a769c93d7f66518e1964367c86161457716506bd.

Revert "Rename UserOfficeWebService environment var"

---

src/auth/questionary/ProposalQuestionaryAuthorizer.ts
src/factory/pdf/proposal.ts

Some authorization flaws are fixed in the PR
- Proposal questionary authorizer 
- PDF generation
E2E
- _ProposalQuestionaryAuthorizer.ts_ The authorization of proposal questionary is following the same logic as for the proposal
- _factory/pdf/proposal.ts_ There was a missing `await`

fix(security): Fixes for authorizers

---

src/datasources/stfc/StfcUserDataSource.ts

Rename UOWS environment variable

---

src/middlewares/graphql.ts

This PR adds a plugin that will redact any error messages that get sent to Apollo Studio.
When preparing these messages, the library uses a copy of the error object, so no data will be lost in error messages that API clients consume.
We want to try using Apollo Studio to provide usage and performance statistics on the GraphQL API.
We only need to add a few environment variables to our kubernetes config to set this up, but by default Apollo will share all GraphQL [error messages (but not query parameters or responses)](https://www.apollographql.com/docs/studio/data-privacy/), and in the past we've noticed that some [sensitive data can be written to logs](https://github.com/UserOfficeProject/stfc-user-office-project/issues/231). Since Apollo Studio is an external service, we want to be …

Prevent error messages being shared with Apollo Studio

---

src/datasources/postgres/TemplateDataSource.ts

This PR aims to fix import of the dependencies
https://jira.esss.lu.se/browse/SWAP-2110
- TemplateDataSource
N/A

fix(import): Import dependencies

---

src/mutations/UserMutations.ts

Without a role a invited user will fail to sign up
To allow for email invites of users

Add role for invited user

---

src/decorators/Authorized.ts
src/middlewares/graphql.ts
src/models/User.ts

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/295
See issue: https://github.com/UserOfficeProject/stfc-user-office-project/issues/295
Tested through creating a script to create 300 proposals, then running it locally before and after the changes. When ran before the changes made, the site would crash and login was not successful. After the changes were made, the site no longer crashes and can log successfully and see all relevant proposals. 
To run it, you'll need to first run:
```
npm install axios
```
Then you can run the script:
```
const n = 300;
const callId = 1;
const grapqlUrl = "http://localhost:8081/graphql";
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMTA1MDM4LCJ1c2VyX3RpdGxlIjoiIiwiZmlyc3RuYW1lIjoiVmVua2F0YSIsIm1pZGRsZW5h …
```

fix: Users with many proposals cannot login

---

src/datasources/postgres/FileDataSource.ts

fix(typescript): Fix typing issues

---

.github/workflows/autoupdate.yaml
README.md

GitHub Action that auto-updates pull requests branches whenever changes land on their destination branch.
Respective PR change for the frontend is here https://github.com/UserOfficeProject/user-office-frontend/pull/807

chore: Automatically update feature branch when base branch changes

---

src/datasources/mockups/QuestionaryDataSource.ts
src/factory/pdf/shipmentLabel.ts
src/models/Shipment.ts

This PR aims to update the label to what we discussed in the latest EAM meeting.
The following changes have been made:
- Added local contact
- Updated facility logo
- Updated additional details
- Using new units
We want to have a label similar to the end result so that we can show stakeholders how is it going to look
https://jira.esss.lu.se/browse/SWAP-2360
https://github.com/UserOfficeProject/user-office-factory/pull/93

feat: updating shipment label

---

package-lock.json
package.json

This PR makes sure that Reviewer puts a comment on the grade.
We want reviewer to add comment when he/she is grading the proposal
https://jira.esss.lu.se/browse/SWAP-2478
- Tests
- Validation Library
- Removed HTML validation for Grade and replaced it with Yup, so user gets consistent user experience
https://github.com/UserOfficeProject/user-office-frontend/pull/843

fix(review): Make grade proposal mandatory

---

package-lock.json
package.json

Update `validation` package to use the latest validation for confirm password.

chore: Update validation package version

---

example.development.env
src/services/assetRegistrar/eam/api/createContainer.ts
src/services/assetRegistrar/eam/api/createTicket.ts
src/services/assetRegistrar/eam/api/getToken.ts
src/services/assetRegistrar/eam/requests/AddAssetEquipment.ts
src/services/assetRegistrar/eam/requests/AddCaseManagement.ts
src/services/assetRegistrar/eam/utils/getEnvOrThrow.ts
src/services/assetRegistrar/eam/utils/performApiRequest.ts

This PR adds new ENV variables and modifies existing ones to be able to use EAM production environment
We want to try out EAM production environment and send an actual package
https://jira.esss.lu.se/browse/SWAP-2509
https://github.com/UserOfficeProject/user-office-frontend/pull/877

fix: Enable to use EAM production environment

---

README.md
example.development.env
src/mutations/AdminMutations.ts
src/services/assetRegistrar/eam/api/createContainer.ts
src/services/assetRegistrar/eam/api/createTicket.ts
src/services/assetRegistrar/eam/api/getToken.ts
src/services/assetRegistrar/eam/requests/AddAssetEquipment.ts
src/services/assetRegistrar/eam/requests/AddCaseManagement.ts
src/services/assetRegistrar/eam/utils/getEnvOrThrow.ts
src/services/assetRegistrar/eam/utils/performApiRequest.ts

Release 28 04 2022

---

package-lock.json
package.json
src/models/questionTypes/FileUpload.ts
src/mutations/AdminMutations.ts

Adds an antivirus scan check to file upload question validation using the [Clamscan](https://www.npmjs.com/package/clamscan) package to interface with an external Clam antivirus service over TCP.
If environment variables `ANTIVIRUS_HOST` and `ANTIVIRUS_PORT` are not both specified the check will be skipped, and if the service cannot be reached the check will also pass. The aim of this was to mirror the current behaviour of the file type check and to not prevent users being able to submit if the service is unavailable for innocent network issues. However, if the preference of reviewers is to have the check fail if the service can't be reached I'm happy to make that change.
The clam antivirus service can be provided in a separate container with simple docker compose config:
```yaml …
```

feat: Run an antivirus scan on uploaded files

---

src/auth/UserAuthorization.ts

This PR fixes the authorization check for SEP members. It would previously return `true` for all users, not just SEP members.
Locally by testing as different users

fix: Fix SEP membership check

---

package-lock.json
package.json

Just upgrade the validation package where we set the new limit for SEP review comment

chore: Upgrade validation package

---

src/eventHandlers/email/stfcEmailHandler.ts

Improved how we identify facility by using the instrument attached to the call rather than the short code.
Emails were sent to correct facility.
part of UserOfficeProject/user-office-project-issue-tracker#638

refactor: Identifying facility using instrument attached to call

---

src/config/stfc/configureSTFCEnvironment.ts

Add user profile URL to fix inconsistency seen in "Logged in as <email>" links.
Ensured links are directing user to the correct page.
Part of UserOfficeProject/user-office-project-issue-tracker#212
Part of  UserOfficeProject/user-office-project-issue-tracker#274
https://github.com/isisbusapps/docker-orchestration/pull/290

refactor: Add user profile URL to fix inconsistency
