Dockerfile.win

Part of UserOfficeProject/stfc-user-office-project#8
Adds a Windows-based Dockerfile. it is mostly identical to the existing one, but with a parameterised `FROM` statement that can take different Windows versions (see [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container) and [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) for why we need separate images for each Windows version). NodeJS does not provide official Docker images for Windows, so the Dockerfile is based on our own NodeJS port hosted on an internal registry.
Aside from the `FROM` statement, the only difference between this and the existing Dockerfile is that the app is copied to `C:\app` instead of …

Add Dockerfile for Windows

---

package-lock.json
package.json
src/eventHandlers/messageBroker.ts
src/queries/UserQueries.ts
src/resolvers/queries/TokenQuery.ts

This pull requests resolves some requirements needed for User office scheduler deployment and includes few additional updates.
- Previously to configure the RabbitMQ only the connection URL was accepted which limits its usability in certain environments.
- Although it is not hard to get the payload of JWT token, I prefer doing it by the dedicated library, this also guarantees the structure of the payload as it is checked by GraphQL
- message broker version updated
- message broker configuration is more flexible 
- if requested the `checkToken` includes the payload of the JWT

SWAP-1113 Deploy

---

src/datasources/InstrumentDataSource.ts
src/datasources/ProposalDataSource.ts
src/datasources/ProposalSettingsDataSource.ts
src/datasources/SEPDataSource.ts
src/datasources/mockups/InstrumentDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/mockups/ProposalSettingsDataSource.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/postgres/InstrumentDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/datasources/postgres/ProposalSettingsDataSource.ts
src/datasources/postgres/SEPDataSource.ts
src/datasources/postgres/records.ts
src/eventHandlers/logging.ts
src/eventHandlers/proposalWorkflow.ts
src/events/applicationEvents.ts
src/models/Proposal.ts
src/models/ProposalEvents.ts
src/mutations/InstrumentMutations.spec.ts
src/mutations/InstrumentMutations.ts
src/mutations/ReviewMutations.ts
src/mutations/SEPMutations.spec.ts
src/mutations/SEPMutations.ts
src/resolvers/mutations/AssignProposalToSEP.ts
src/resolvers/mutations/AssignProposalsToInstrumentMutation.ts
src/resolvers/types/ProposalWorkflow.ts
src/workflowEngine/index.ts

Create the proposal workflow engine that reacts on proposal events and updates the proposal status based on the proposal workflow and rules that are set in that workflow.
This change is part of the proposal workflow implementation.
It is tested with e2e tests using cypress on the frontend that covers the whole workflow feature.
It fixes SWAP-1131 Jira task and it is part of https://github.com/UserOfficeProject/ess-user-office-project/issues/4
Created new database table proposal_events that holds all events that can happen on proposal to be able to track events that are done/not done. Added workflow engine functionality to be able to handle proposal events and send proposals to the engine for status checks and changes. Fixed some bugs found on the way.

Swap 1131 proposal workflow and status engine

---

.dockerignore
.gitignore
example.env
index.ts
package-lock.json
package.json
src/middlewares/pdfFactory.ts

Added support for an external, plug-in PDF creator, on the backend we just collect the data we want in the PDF and we send it to the external service. The current solution waits for the PDF, in the future it should be async and poll based.
The previous solution uses hard coded templates / structure, and it's hard to extend or add support for new PDFs.
The goal here is to collect the information we need send it to an external system which handles the PDF creation.
Currently there are no tests, will be added in a different ticket/PR.
https://jira.esss.lu.se/browse/SWAP-1143
- new code added which focuses on collecting the data
- feature flag added to use the old system until it's completely removed and tests added

SWAP-1143 Artifact factory

---

.github/CODEOWNERS

This is to trial using GitHub [`CODEOWNERS`](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) to help us manage the incoming reviews on the STFC side. Code owners are available for public repos for free organisations; however, I'm not sure if the team allocation works for free organisations.
It adds `@UserOfficeProject\user-programme` as a code owner.
It hasn't been tested yet so we will need to watch out for the next PR.

Add stfc-user-programme as codeowners

---

src/datasources/mockups/QuestionaryDataSource.ts
src/datasources/postgres/TemplateDataSource.ts
src/datasources/postgres/records.ts
src/models/Template.ts

Fixing bug where dependency was not saved
unit tests
e2e tests
manual tests
SWAP-1233
The input for dependency is passed as an object but was taken in as two separate fields.
N/A

SWAP-1233 #resolved

---

db_patches/0072_ExtendMimeTypeField.sql
src/middlewares/files.ts

This is a bugfix for failing to upload docx files.
The reason for failure was DB VARCHAR(64) which was too short for long docx mimetype.
Additionally to fix the fix was added where now the backend will return the appropriate HTTP status code 500 in case file upload fails
unit tests
SWAP-1230
https://github.com/UserOfficeProject/user-office-frontend/pull/108

SWAP-1230 docx upload fix #resolved

---

db_patches/0069_AddProposalIdToSamples.sql
db_patches/0073_CleanupIncompleteSanples.sql

Fixes broken samples on the test server, and adds DB constraints
Some samples have no proposal_id, these are samples that haven't been completed and added to the proposal, therefore they ought to be deleted
N/A
Added db script
N/A

Cleanup incomplete samples

---

db_patches/0073_UpdateProposalView.sql
src/datasources/postgres/records.ts
src/models/ProposalView.ts
src/resolvers/types/ProposalView.ts

This PR aims to fix an issue related to the Proposals table, where the connected SEP doesn't show up.
The Proposals table uses a view to display the relevant information we need, this view used an obsolete field to populate the SEP code.
This PR removes the unused field and updates the view.
https://jira.esss.lu.se/browse/SWAP-1228
- `proposal_view_table` updated
- obsolete `sep_id` field removed
- field names updated
https://github.com/UserOfficeProject/user-office-frontend/pull/107
https://github.com/UserOfficeProject/user-office-backend/pull/86

SWAP-1228 Table is missing data after SEP deactivation

---

db_patches/0074_MigrateFiesToUUID.sql

Store file id as UUID instead of bigint
File ID used to be BIGINT (2^53 - 1), which has conversion problems to JS number which max number is smaller than Postgres BIGINT. This takes care of storing file id as UUID which is converted to string in JS.
Also, the file ID is a long UUID which is hard to guess as we don't have authentication for downloading files for now. 
SWAP-1157
Altering database
Migrating data
N/A

SWAP-1157 #resolved

---

src/datasources/SEPDataSource.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/postgres/SEPDataSource.ts
src/datasources/postgres/UserDataSource.ts
src/datasources/postgres/records.ts
src/mutations/SEPMutations.spec.ts
src/mutations/SEPMutations.ts
src/resolvers/mutations/AssignMembersToSEP.ts

Being able to remove SEP_Chair or SEP_Secretary and fixing of a found bug in reassigning roles from people settings page.
As a user officer you should be able to remove SEP_chair or SEP_secretary from SEP. Also when adding new role to a user it was removing some important information about sep_id if some role is attached to a SEP.
E2E tests on the frontend
https://jira.esss.lu.se/browse/SWAP-903
Changes are mainly on the logic layer and fixing some types.

SWAP-903 #resolve and keeping sep_id when removing roles fixed

---

db_patches/0000_init.sql
db_patches/0013_AlterUsersEmailInvite.sql
src/datasources/UserDataSource.ts
src/datasources/mockups/UserDataSource.ts
src/datasources/postgres/UserDataSource.ts
src/mutations/UserMutations.ts
src/resolvers/mutations/UpdateUserMutation.ts

This PR adds support to manually verify email and remove the placeholder flag from a user account.
As it is now, it is not possible to do this manually as a User Officer.
https://jira.esss.lu.se/browse/SWAP-1188
- API endpoints added for the manual updates
- e2e tests related seeds added
https://github.com/UserOfficeProject/user-office-frontend/pull/138

SWAP-1188 As a user officer I should be able to verify users

---

src/mutations/FileMutations.ts

This fixes broken downloads.
The construction of the downloads folder was removed from the dockerfile, presumably by accident.
To prevent this from happening in the future the code itself will now create the folder if it does not exist.

Fix missing downloads directory

---

src/datasources/postgres/ProposalDataSource.ts

This is a fix for wrong table name when querying proposals by shortCode

fix wrong table name

---

src/eventHandlers/email.ts

This will remove the "errors" from the logs, also helps with following what email should have been sent

Use a no-op function in development for sending email.

---

src/queries/ReviewQueries.ts
src/resolvers/types/Review.ts

This PR fixes the empty "External reviews" table on the final ranking form.
Right now it's not visible because of permission issues.
- required permission to access proposal reviewers list
- model used to query the reviewer's data
https://github.com/UserOfficeProject/user-office-frontend/pull/207

SEP Bugfix: let SEP Chair/Secretary access reviews

---

src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/resolvers/types/Call.ts

Adding `proposalCount` resolver on the call.
To be able to see how many proposals are on the call.
e2e tests
https://jira.esss.lu.se/browse/SWAP-1381

Swap 1381 call proposal count

---

src/mutations/SEPMutations.ts

At the moment a proposal can have multiple SEP's assigned to it, this will cause the proposal to appear multiple times in the list
See above

Hot fix for SEP assigment

---

src/datasources/postgres/SEPDataSource.ts
src/mutations/SEPMutations.ts
src/resolvers/types/Proposal.ts
src/resolvers/types/SEPProposal.ts
src/utils/UserAuthorization.ts

This PR fixes two SEP related bugs:
- proposals not in SEP_ status weren't accessible in the final ranking form: fixed
- it's possible to have proposals that have their instrument submitted but this is not visible on the UI: fixed
- return proposals in sep final ranking form regardless of their current status
- include the instrument-submitted flag for each proposal
https://github.com/UserOfficeProject/user-office-frontend/pull/246

sep bugs fixed

---

db_patches/0081_AlterInstrumentHasProposalTable.sql

This PR changes the on delete action of `instrument_has_proposal`.`proposal_id` so when we delete a proposal we also delete the related instrument-proposal connection.

Delete instrument-proposal connection when proposal is deleted

---

src/buildContext.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/mockups/UserDataSource.ts
src/mutations/SEPMutations.spec.ts
src/mutations/SEPMutations.ts

This PR introduces some additional checks to User-to-SEP assignment: only users with SEP Reviewer role can become SEP Chair/Secretary (obviously by following the normal flow).
Currently, any user can be selected.
- require users to have SEP Reviewer role to assign to SEP as a SEP Chair/Secretary
https://github.com/UserOfficeProject/user-office-frontend/pull/248

Allow only SEP Reviewers to become SEP Chair/Secretary

---

src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/mutations/ProposalMutations.ts

Reset proposal events that are coming after given status. For example if proposal had SEP_REVIEW status and we manually reset to FEASIBILITY_REVIEW then events like: proposal_feasible, proposal_feasibility_review_submitted and proposal_sep_selected should be reset to false in the proposal_events table
Previously if we manually reset proposal status the events were staying in the state they are nothing was changed there to reset them at the point where proposal is returned.
manual tests
https://jira.esss.lu.se/browse/SWAP-1410
Added new method for reseting proposal events inside proposal data source.

SWAP-1410 #resolved

---

db_patches/0086_AddProposalStatusUpdatedEvent.sql
src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/eventHandlers/logging.ts
src/eventHandlers/proposalWorkflow.ts
src/events/applicationEvents.ts
src/events/event.enum.ts
src/mutations/ProposalMutations.ts
src/resolvers/mutations/AssignProposalsToInstrumentMutation.ts
src/resolvers/mutations/ChangeProposalsStatusMutation.ts

Status change on multiple proposals at once
Previously if you wanted to change proposal status you should do it manually one by one proposal.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-1396

Swap 1396 change status on multiple proposals

---

src/factory/xlsx/sep.ts
src/middlewares/factory/xlsx.ts

This PR fixes the filename for SEP XLSX export and also changes the sep time allocation fallback to technical review's time allocation.
Currently, if there is more than one instrument for a given SEP & call pair, the filename is not set properly.
https://jira.esss.lu.se/browse/SWAP-1490
- sep xlsx: fix filename for collection
- if sep time is not set fallback to technical review time

SWAP-1490 The file name when downloading xls file is unknown

---

src/datasources/postgres/ProposalDataSource.ts

Because of the join I think there was conflict with the `submitted` fields from `proposal` table and `instrument_has_proposals` table and it was taking the one from `instrument_has_proposals`. We don't need that one in this query and I did more specific selection so this field is excluded and the one from proposals table is used.
manual tests
https://jira.esss.lu.se/browse/SWAP-1508

SWAP-1508 #resolved

---

Dockerfile.dev.win
Dockerfile.win

We've recently renamed our Node base image, so we just have to update the Dockerfiles to match the new name.
Note that the "prod" Dockerfile uses a specific Node version, while the dev version just pulls the lastest Node 12.x.
We're trying to have simpler names for our base images.
Internally, this is part of isisbusapps/docker-base-images#39.
The Dockerfiles were built locally.

Update Windows base image names

---

src/config/dependencyConfigSTFC.ts

Removes the RabbitMQ handler from the STFC dependency config, as we're not currently running RabbitMQ.
This removes a lot of errors in the backend logs about not being able to connect to RabbitMQ.
Tested locally on my PC

Disable RabbitMQ handler in STFC config

---

db_patches/0091_CleanupQuestionaryDataAfterDelete.sql
example.env
src/mutations/ProposalMutations.ts

This PR adds cleanup routines that clean up questionnaire data when proposal, sample or shipment is deleted.
When for example proposal is deleted we also want to  make sure that all relevant data is cleaned up
SWAP-1526
N/A

Swap 1526 Clean up questionnaire data

---

src/decorators/ValidateArgs.ts
src/models/questionTypes/RichTextInput.ts
src/mutations/AdminMutations.ts
src/mutations/ProposalMutations.ts
src/mutations/ReviewMutations.ts
src/mutations/SEPMutations.ts

Because of the change in the frontend from normal textarea to richtext input we need to sanitize the html string on every input where it is needed. The check is added inside `ValidateArgs` decorator and it sanitizes the input args passed as second parameter on the decorator.
e2e tests
https://jira.esss.lu.se/browse/SWAP-1523

sanitize input html from rich text editor

---

.github/workflows/build-push.yml
.github/workflows/github-tag-and-release.yml
.github/workflows/github_tag_and_release.yml

A GitHub Action to automatically bump and tag master, on merge of a pull request.
Previously this was done manually to tag and create a release.
Manual tests
https://jira.esss.lu.se/browse/SWAP-1474
Added new github action called `github-tag-and-release`

try new tag and release action

---

src/mutations/SampleMutations.ts
src/mutations/UserMutations.ts
src/queries/CallQueries.ts
src/utils/QuestionaryAuthorization.ts
src/utils/SampleAuthorization.ts
src/utils/ShipmentAuthorization.ts

isUserOfficer is a synchronous method, but many places in the code it was used as async.
Cleaning up and improving readibility
N/A

patch: Remove unnecessary awaits for isUserOfficer

---

src/models/questionTypes/Date.ts
src/resolvers/types/FieldConfig.ts

This PR aims to add functionality so that user can add time when specifying date. The time is optional and can be configured per question basis.
The datetime is stored in the database in ISO datetime format, without timezone. ISO specification therefore says that without timezone formatted time means that time is in local timezone. We are omitting the timezone due to lack of good support for that in JS date object and datetime pickers. 
SWAP-1601
https://github.com/UserOfficeProject/user-office-frontend/pull/392

feat: Adding time to DateComponent

---

db_patches/0095_SetAuthFeatureFalse.sql

Disable external auth feature flag, for now until we can separate db_patches so that the flag do not interfere with e2e tests
SWAP-1643
db patches

Disable external auth feature flag

---

db_patches/0097_AddFooterPageContent.sql
src/models/Page.ts
src/models/questionTypes/RichTextInput.ts

This adds another page for footer content that accepts user input. It displays at the bottom of the page above the existing privacy and faq links.
As with the privacy and faq links, if there is no content defined, it won't be shown. So one or the other can be shown.
STFC needs a way of being able to show custom content in the footer that may be subject to change over time.
Just tested locally by having a play with adding/removing content.
Part of UserOfficeProject/stfc-user-office-project#141
Doesn't close the issue because we'll eventually need a STFC-specific patch to add the actual content.
Frontend changes - https://github.com/UserOfficeProject/user-office-frontend/pull/414
Please take notice of commit af53674 - this allows links when sanitising the HTML input. Links wouldn't work …

Allow for customisable footer content

---

src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/mutations/AdminMutations.ts
src/mutations/VisitMutations.spec.ts
src/mutations/VisitMutations.ts
src/resolvers/types/User.ts

This PR aims to fix user story "As a user I want to see only accepted proposals when signing up for a visitation, so that I do not make any unnecessary mistakes"
SWAP-1630
https://github.com/UserOfficeProject/user-office-frontend/pull/417

feat: Visitations can be only about accepted proposal BREAKING CHANGE

---

src/mutations/AdminMutations.ts

Feature enabling PR is not taking into account that features also need to be enabled when the DB is restarted

Enable features after reset db

---

src/datasources/VisitDataSource.ts
src/datasources/mockups/VisitDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/datasources/postgres/VisitDataSource.ts
src/utils/UserAuthorization.ts

Up until now the proposal was visible only by the PI and CO-proposers. However, it is likely that visitors visiting the facility and running the experiment is neither PI nor co-proposal. Also visitors need to see the information about the proposal.
This PR enables visitors to see the proposal,
Additionally it improves database performance when proposals are selected, by having lighter query.
SWAP-1660
https://github.com/UserOfficeProject/user-office-frontend/pull/434

feat: Visitor should see the proposals he is supposed to visit

---

package-lock.json

Closes UserOfficeProject/stfc-user-office-project/issues/189
I've tried removing and reinstalling all NPM packages which required the "missing" module (`underscore`). In some case, it was just a dependency of a dependency.
The full list of modules I reinstalled was:
- `soap`
- `email-templates`
- `newman` (dev only)
- `@stfc-user-programme/uows_client_generator` (dev only)
I'm not too sure why this fixed the problem, but the backend now starts up fine with the STFC config.
Closes UserOfficeProject/stfc-user-office-project/issues/189
Built the backend container on my PC, then tried starting it up. Also checked that the frontend could still connect while it was running

Reinstall modules that require the underscore package

---

db_patches/0104_AddScheduledEventIdToRiskAssessments.sql
src/datasources/RiskAssessmentDataSource.ts
src/datasources/mockups/RiskAssessmentDataSource.ts
src/datasources/postgres/RiskAssessmentDataSource.ts
src/datasources/postgres/records.ts
src/models/RiskAssessment.ts
src/mutations/RiskAssessmentMutations.spec.ts
src/mutations/RiskAssessmentMutations.ts
src/mutations/VisitMutations.ts
src/queries/RiskAssessmentQueries.ts
src/resolvers/mutations/CreateRiskAssesssment.ts
src/resolvers/mutations/UpdateRiskAssessmentMutation.ts
src/resolvers/types/RiskAssessment.ts

This PR aims to fix the issue that there could be multiple risk assessments for experiments if there are multiple risk assessments. Each risk assessment should indicate which sample materials are the risk assessment for.
Added E2E tests
https://jira.esss.lu.se/browse/SWAP-1731
https://github.com/UserOfficeProject/user-office-frontend/pull/524

feat: Attach risk assessment to the experiment time [Swap-1731]

---

src/middlewares/graphql.ts

'One line' change that keeps original config but otherwise explicitly sets playground to false if in production.
[Default behaviour](https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/) is that this should be disabled in production anyway -- I'm wondering if it was being enabled (even partially) by the explicit setting of `schema.polling.enable`. This should no longer occur.
I've tested this by changing `production` to `development`, which disables the playground entirely in the local environment. I would expect the exact same behaviour on prod.  
The URL can still be pinged so this won't break the [prod backend monitoring job](https://ci.devs.facilities.rl.ac.uk/view/ProposalSubmission/job/Prod_Test.Ping_ProposalBackend/) -- this tested by running the exact …

Disable GraphQL Playground if in Production

---

src/middlewares/graphql.ts

I missed a typo in my previous PR for this issue: `process.end.NODE_END` --> `process.end.NODE_ENV`.  
I have corrected this here.
Details otherwise match the [aforementioned PR](https://github.com/UserOfficeProject/user-office-backend/pull/407).

GraphQL Playground Issue Typo Correction

---

src/mutations/SampleMutations.ts
src/resolvers/mutations/CloneSampleMutation.ts

This PR aims to improve the user experience when cloning sample
Currently, when cloning a sample it clones it with the title 'Copy of <original title>". Most often the user will then click the item to rename it.
With this change when the user wants to copy a sample the prompt is presented asking to enter the new title of the sample.
-[x] E2E
https://github.com/UserOfficeProject/user-office-frontend/pull/551

Improve user experience when cloning sample

---

src/datasources/stfc/StfcUserDataSource.spec.ts
src/datasources/stfc/StfcUserDataSource.ts

Refs https://github.com/UserOfficeProject/stfc-user-office-project/issues/208
Give instrument scientist role to user officers (and developers), allowing mapping from one-to-many for roles.. This also makes the code more explicit in what it's trying to achieve.
Fixes https://github.com/UserOfficeProject/stfc-user-office-project/issues/208
Tested using unit tests and running in frontend

fix: Give instrument scientist role to user officers (and developers)

---

src/models/questionTypes/RichTextInput.ts

sanitizeHtml was added for checking contents but was not allowing enough tags or styles to make sufficient HTML content. This allows more tags and also removes the check for what styles are allowed
For user officer to be able to set HTML content with <div style="xxx">

Added div, br to allowed tags and allow all styles

---

.eslintrc
index.ts
src/eventHandlers/email.ts
src/eventHandlers/logging.ts
src/factory/service.ts
src/middlewares/factory/pdf.ts
src/populate/executor.ts
src/populate/index.ts
src/utils/jwt.ts

Loosely related to UserOfficeProject/stfc-user-office-project#231
Replaces all `console.log()` occurrences with calls to `duo-logger`.
The PR also introduces a new ESLint rule to avoid using `console.log()` in the future. Some developer scripts have been excluded from this new rule as it's not relevant for them.
Originally done as part of UserOfficeProject/stfc-user-office-project#231, I'm creating a separate PR as the main issue is blocked by not being able to push to NPM.
Using duo-logger for all messages ensures that all log output is formatted in the same way, allowing us to parse and monitor it with tools like Elasticsearch.
It also makes it easier to see where messages are being logged, and to replace the default logger if necessary.
Checking the logs for relevant events on my local …

refactor: Use duo-logger instead of console in the backend

---

package-lock.json
package.json
src/utils/buildFederatedSchema.ts

Upgrade some of the `@apollo` packages to align with `user-office-scheduler-backend`. Also fixed some errors after upgrading the `@apollo/subgraph`.
Its better to keep both backends aligned with dependencies to avoid some incompatibilities on the gateway.

Upgrade packages to align with scheduler backend versions

---

src/services/eam/requests/AddAssetEquipment.ts
src/services/eam/requests/AddCaseManagement.ts

Closes SWAP-2160
Month in JS is 0-based but in C# 1 based, this caused an inconsistency
In January creating new containers and issues in EAM started to fail
https://jira.esss.lu.se/browse/SWAP-2160
EAM requests
N/A

fix(eam): Month in JS is 0-based but in C# 1-based

---

package-lock.json
package.json
src/datasources/stfc/StfcUserDataSource.spec.ts
src/datasources/stfc/StfcUserDataSource.ts
src/datasources/stfc/UOWSSoapInterface.ts
src/datasources/stfc/__mocks__/UOWSSoapInterface.ts
src/mutations/UserMutations.ts

Closes https://github.com/UserOfficeProject/stfc-user-office-project/issues/231
The main point of this PR is to pull in the changes from https://github.com/UserOfficeProject/user-office-lib/pull/83. Most notably, this stops the app from logging raw requests to the UOWS whenever a request fails, and makes the UOWS client throw exceptions when a request has failed.
The second commit improves the error handling for failed logins and logout, making sure that all errors are logged nicely.
This prevents prod API tokens from appearing in the STFC logs.
By trying to authenticate with an invalid and a valid token on my local machine. We still don't have a way of testing this automatically.

Remove sensitive and verbose logs

---

package.json

Part of UserOfficeProject/stfc-user-office-project#312
This prevents us from picking up any future updates, now that the package has been compromised.
NPM packages are immutable once uploaded, so as long as the faker package isn't completely deleted we should be safe.

Pin Faker version to 5.5.3

---

src/auth/EsiAuthorization.ts
src/datasources/ScheduledEventDataSource.ts
src/datasources/mockups/ScheduledEventDataSource.ts
src/datasources/postgres/ScheduledEventDataSource.ts
src/mutations/FeedbackMutations.ts
src/mutations/ProposalEsiMutations.ts
src/mutations/VisitMutations.ts
src/queries/ScheduledEventQueries.ts
src/resolvers/queries/ScheduledEventsCoreQuery.ts
src/resolvers/types/ExperimentSafetyInput.ts
src/services/eam/index.ts

This is to avoid conflicts in naming between core and scheduler
When using Apollo Federation, endpoint names must not clash.
There was a clashing query named ScheduledEvent

fix(scheduled-event): renaming scheduledEvent to scheduledEventCore

---

Dockerfile.dev

Part of UserOfficeProject/stfc-user-office-project#313
On Node 16, running as root can cause NPM to fail due to permission errors. It's safer to run as a non-root user.

Run dev Docker container as Node user

---

src/datasources/stfc/StfcProposalDataSource.ts

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/318
Instrument scientist unable to filter by question 
Tested through logging on as a Instrument Scientist and using the question filters.
fixes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/318
File changed: `StfcProposalDataSource.ts`

fix: instrument sci unable to filter by question

---

src/mutations/UserMutations.ts

Currently, there is incomplete information about the error when it happens. This PR will add more details to the 'can not verify user' error log

fix: add more logs to verify user error

---

src/mutations/UserMutations.ts

When a user tried to verify a email it would fail if the user record had already been updated after the verify token had been created, this would lead to false errors as email clients tried visiting the verify url again. This PR allows a verify to happen multiple times and after the user record has been updated
Remove false positives
Locally

fix: Allow users to verify email after user update to avoid false error messages

---

src/eventHandlers/messageBroker.ts

Removing a debug message that caused confusion and alarm
We want to be alarmed about issues that we need to look at. Even though this was a debug message this has caused quiet of alarm when happening in production however there is no need to worry in these scenarios when the debug message was logged.
https://jira.esss.lu.se/browse/SWAP-2232
- messageBrokker
N/A

fix: remove alarming message

---

src/auth/ProposalAuthorization.ts
src/auth/ReviewAuthorization.ts
src/auth/TechnicalReviewAuthorization.ts
src/mutations/ReviewMutations.ts
src/queries/ReviewQueries.ts
src/resolvers/queries/ReviewQuery.ts

This PR refactors and fixes review authorization
This PR 
- moves authorization into ReviewAuthorizer and TechnicalReviewAuhtorizer components, and then reuses the logic in mutations
- allows read/write rights to only those reviewers who have been assigned to do the review/technicalReview
https://jira.esss.lu.se/browse/SWAP-2480
- Added authorizers
- Changed corresponding to use Authorizers
https://github.com/UserOfficeProject/user-office-frontend/pull/842

fix: SEP reviewer should only read/write reviews he/she can review

---

src/eventHandlers/messageBroker.ts

Refs: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/519
At stfc were using a different vhost for rabbitmq so we need a way to set that in the backend.
If the vhost variable is not set the default value is used.
https://github.com/isisbusapps/docker-orchestration/pull/237
BisAppSettings: stfc-user-office-project-519-rabbitmq-prod-config

Added option for different rabbitmq vhost

---

src/datasources/SEPDataSource.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/postgres/SEPDataSource.ts
src/queries/SEPQueries.ts
src/resolvers/queries/SEPQuery.ts

Using null which is much more understandable than 0 for loading all sep proposals when filtering by call.
Previously we were sending 0 from the frontend as a callId in the filter which wasn't that clear.
- e2e tests
- manual testing
https://jira.esss.lu.se/browse/SWAP-2467
https://user-images.githubusercontent.com/6333063/163117850-a61de3d8-9acd-40bd-ad2c-b9ea219152bf.mp4
Frontend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/856

fix: Use null instead of 0 for sep proposals call filtering when we want to query all calls

---

src/mutations/AdminMutations.ts

When getting or trying to mutate some data right after the `resetDB` call we were getting errors all the time because call finishes before setting up the environment properly. This was because we were not waiting for environment configure to finish.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2444
Frontend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/875

fix: Fixing possible race condition when calling resetDB

---

src/datasources/postgres/database.ts

This PR adds an error message to Query Error logs. This is an important message for debugging as it contains the actual reason for the failure. It appears that some properties are not stringified (including `message`) from the error object.
We want clear error messages so that we can see the reason what is causing it
database.ts
N/A

fix: adding reason why query error happened

---

src/auth/ReviewAuthorization.ts
src/datasources/mockups/ReviewDataSource.ts
src/datasources/mockups/UserDataSource.ts
src/mutations/ReviewMutations.spec.ts
src/mutations/ReviewMutations.ts

SEP Chair and SEP Secretary should not be able to change already submitted reviews and can not un-submit as well.
Previously SEP Chair and Secretary were allowed to do any action on the SEP reviews.
- manual tests
- unit tests
- e2e tests
https://jira.esss.lu.se/browse/SWAP-2474
Frontend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/873

feat: Remove access for SEP chair and secretary to un-submit or change submitted reviews

---

db_patches/0120_AddQuestionDependenciesOnDeleteCascade.sql

This PR adds DB cleanups to make sure there are no dangling references to relations that does not exist
the dependencies between questions should be cleaned up when:
- the question is removed from the template;
- the question is deleted
Added DB patch

fix: This PR fixes dangling references in question_dependencies

---

src/mutations/TemplateMutations.ts

Mark template as active after import, if there is no active template already
As a user officer I expect the template to be set up right away after the import
N/A

fix: mark default template after import

---

src/datasources/postgres/TemplateDataSource.ts

First commit is just ESLint / inspection changes
Second commit handles the case for template description being empty string `""` These templates are returned as valid from `mutation validateTemplateImport` but would not return properly due to the previous check `!data.template.description`
I have changed this to check for null and undefined only now.
Templates with description as empty string are returned as valid from `mutation validateTemplateImport` but would not return properly due to the previous check `!data.template.description`
I have changed this to check for null and undefined only now.
Manual API testing

Allow empty string template descriptions

---

db_patches/0122_RevertAddCallInstrumentsToProposalView.sql
src/datasources/postgres/ProposalDataSource.ts
src/datasources/postgres/records.ts
src/datasources/stfc/StfcProposalDataSource.ts

Reverts the recent changes (https://github.com/UserOfficeProject/user-office-backend/pull/658) to the proposal table view which produced duplicate records when the proposal was assigned to a call with multiple instruments.
STFC still needs to show proposals for a call's instrument rather than proposals directly assigned to an instrument, so the logic for doing this has been moved to the STFC ProposalDataSource. This will likely slow down the STFC instrument scientist page, but avoid the complexity of making the DB view change work for both facilities.
Note that the STFC datasource relies on the assumption that we won't be using the proposal's assigned instrument there: it only looks at the call instrument. This will break if we ever start assigning proposals directly.
- Manual testing on …

Remove duplicate proposals in instrument scientist view

---

.prettierignore
package-lock.json
package.json
src/auth/StfcUserAuthorization.ts
src/auth/UserAuthorization.ts
src/datasources/stfc/StfcUserDataSource.ts
src/datasources/stfc/UOWSSoapInterface.ts
src/datasources/stfc/__mocks__/UOWSSoapInterface.ts

Regenerates the UOWS client using the latest generator version. This includes changes which reduce calls made to the UOWS (from https://github.com/UserOfficeProject/user-office-lib/pull/131 and https://github.com/UserOfficeProject/user-office-lib/pull/134). The result of this should be much more reliable communication with the UOWS, reducing the problem of users being logged out when the UOWS receives too many requests. When testing locally, my setup has gone from reliably logging me out whenever I access the User Officer dashboard to always working on all pages I tested.
As part of this, Typescript was automatically updated to its latest version, because the `uows-client-generator` package now requires a later version of Typescript than the one previously used in this app. The ESlint …

fix: Prevent random STFC logouts by reducing UOWS requests

---

src/datasources/SEPDataSource.ts
src/datasources/mockups/SEPDataSource.ts
src/datasources/postgres/SEPDataSource.ts
src/resolvers/types/SEP.ts
src/resolvers/types/SEPReviwers.ts

All SEPs have number of proposals in the table view and SEP members now have number of proposals they need to review. 
It was hard to know about number of proposals which SEP member is responsible to review
- e2e tests
- unit tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2597
Frontend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/935

feat: Add proposals count to SEPs and SEP members

---

src/datasources/ProposalDataSource.ts
src/datasources/mockups/ProposalDataSource.ts
src/datasources/postgres/ProposalDataSource.ts
src/datasources/postgres/SEPDataSource.ts
src/queries/SEPQueries.ts

Now every SEP reviewer will be able to see SEPs that he is part of and view the proposals inside. After submitting the review and if all reviews are submitted then he/she can see all reviews on proposal.
Previously SEP reviewer wasn't able to see SEPs and only able to see his own proposals that he needs to grade.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2598
https://user-images.githubusercontent.com/6333063/172836699-21f28250-c291-4a37-a4a6-7de104889804.mp4
Backend PR: https://github.com/UserOfficeProject/user-office-backend/pull/669

feat: Make SEPs and SEP Proposals visible to SEP_Reviewer

---

src/auth/UserAuthorization.ts

This query
```
query {
proposals(filter: { instrumentId: 4 }) {
proposals {
proposer {
firstname
}
}
}
}
```
Will fail if requested with the API access token with reading privileges
I believe this change is related to https://github.com/UserOfficeProject/user-office-backend/issues/678 , so please any feedback from @martin-trajanovski is appreciated because you looked into similar issue with SEP.

fix: grant reading users for access token

---

src/datasources/mockups/UserDataSource.ts
src/datasources/postgres/records.ts
src/datasources/stfc/StfcUserDataSource.ts
src/models/User.ts
src/queries/UserQueries.ts
src/resolvers/types/BasicUserDetails.ts
src/resolvers/types/Proposal.ts

This PR aims to add the organizationId to the BasicUserDetails so we would be able to use that when we compare on the frontend.
Previously only organization name was returned which is not relevant to compare by.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2493
https://user-images.githubusercontent.com/6333063/173020479-270a7b87-63af-475d-8739-40ffda147d40.mp4
Frontend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/945

feat: Add organizationId to the basic user details to be able to use it on the frontend

---

src/models/questionTypes/FileUpload.ts

This is a hotfix that treats 0 in the PDF file upload page limit as unlimited. I missed this logic out when I did this work, sorry.
As mentioned in https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/625, we can work around this for now by setting a different page limit.

fix(pdf file upload): Hotfix for unlimited PDF page limit

---

src/auth/StfcUserAuthorization.spec.ts
src/auth/StfcUserAuthorization.ts

This fixes instrment scientists (and others) not being assigned to instruments.
We were filtering out all of the non duplicate roles, instead of the inverse. On dev and for me at least, the "User Officer" role was the only duplicate, which is probably why we didn't notice.
Part of UserOfficeProject/user-office-project-issue-tracker#628

fix: Hotfix for STFC instrument assignment

---

src/datasources/stfc/StfcUserDataSource.spec.ts
src/datasources/stfc/StfcUserDataSource.ts
src/datasources/stfc/__mocks__/UOWSSoapInterface.ts

(View without whitespace changes)
This is a hotfix that fixes an error when searching for a user to add as PI or Co-I, when the UOWS returns no results.
Refs UserOfficeProject/user-office-project-issue-tracker#632
- Tested that a frontend error displays rather than the backend throwing an error
- Fix aligns with the backend error thrown

fix: Fix STFC email search

---

package-lock.json
package.json
src/middlewares/graphql.ts

Refs https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/645
Refs https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/18
Adds an error logging plugin which puts any GraphQL errors to the logging framework. Using `info` as an error over GraphQL might not actually be an error.
Currently looking at load testing our services and they don't let the server know when they've failed, if there's been failed requests. In addition, this means we're not relying on the client providing information to the server.
Running the application locally and E2E using https://github.com/UserOfficeProject/user-office-frontend/pull/993.
N/A - just part of other issues
Creates a simple plugin and adds it to the `src/middlewares/graphql.ts`.
N/A

feat: add logging on error
